In [1]:
import numpy as np
import pandas as pd

# DataFrame 객체 생성

DataFrame 객체는 2차원 형태의 Dictionary, List, numpy.ndarray 같은 데이터를 넣어 만든다.

index, columns를 직접 지정하여 원하는 라벨을 붙일 수 있다.

In [2]:
data = [
    ['Alice', 20, 'Seoul'],
    ['Bob', 25, 'Incheon'],
    ['Charlie', 30, 'Busan']
]

pd.DataFrame(data, index=['row1', 'row2', 'row3'], columns=['name', 'age', 'city'])

         name  age     city
row1    Alice   20    Seoul
row2      Bob   25  Incheon
row3  Charlie   30    Busan

index, columns를 지정하지 않으면 0, 1, 2, ... 같은 정수 인덱스를 자동으로 붙인다.

In [3]:
pd.DataFrame(np.arange(12).reshape(3, 4))

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

딕셔너리로 만들면 키를 컬럼 라벨로 사용한다.

In [4]:
data = {
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [20, 25, 30],
    'city': ['Seoul', 'Incheon', 'Busan']
}

pd.DataFrame(data)

      name  age     city
0    Alice   20    Seoul
1      Bob   25  Incheon
2  Charlie   30    Busan

DataFrame.values로 데이터를 확인할 수 있다.

In [5]:
data = [
    [90, 80, 70],
    [85, 95, 75],
    [90, 85, 80]
]
df = pd.DataFrame(data)

df.values

array([[90, 80, 70],
       [85, 95, 75],
       [90, 85, 80]])

DataFrame.columns로 컬럼 라벨을 확인하고, 바꿀 수 있다.

In [6]:
df.columns = ['math', 'english', 'science']
df.columns

Index(['math', 'english', 'science'], dtype='str')

DataFrame.index로 인덱스 라벨을 확인하고, 바꿀 수 있다.

In [7]:
df.index = ['Alice', 'Bob', 'Charlie']
df.index

Index(['Alice', 'Bob', 'Charlie'], dtype='str')

DataFrame.columns.name으로 컬럼 이름을 확인하고 바꿀 수 있다.

In [8]:
df.columns.name = 'Subject'
df.columns.name

'Subject'

DataFrame.index.name으로 인덱스 이름을 확인하고 바꿀 수 있다.

In [9]:
df.index.name = 'Student'
df.index.name

'Student'

# DataFrame 인덱싱

컬럼 라벨을 사용해 컬럼을 인덱싱할 수 있다.

인덱싱 결과는 Series이다.

In [10]:
df['english']

Student
Alice      80
Bob        95
Charlie    85
Name: english, dtype: int64

리스트 인덱싱으로 여러 컬럼을 고를 수 있다.

인덱싱 결과는 DataFrame이다.

In [11]:
df[['math', 'science']]

Subject  math  science
Student
Alice      90       70
Bob        85       75
Charlie    90       80

슬라이싱으로 여러 행을 고를 수 있다.

In [12]:
df[:2]

Subject  math  english  science
Student
Alice      90       80       70
Bob        85       95       75

인덱스 라벨을 사용해 슬라이싱할 수 있다.

정수 인덱스과 달리 끝 라벨의 행을 포함한다.

In [13]:
df[:'Charlie']

Subject  math  english  science
Student
Alice      90       80       70
Bob        85       95       75
Charlie    90       85       80

컬럼 라벨과 인덱스 라벨을 모두 사용해 원소 하나만 인덱싱할 수 있다.

In [14]:
df['english']['Alice']

np.int64(80)

컬럼 라벨을 지정하지 않은 경우에만 정수 인덱싱을 사용할 수 있다.

In [35]:
df = pd.DataFrame(np.arange(12).reshape(3, 4))
df[2]

0     2
1     6
2    10
Name: 2, dtype: int64

리스트의 리스트 형태를 사용하여 계층으로 라벨을 지정할 수 있다.

In [41]:
df.columns = [['c12', 'c12', 'c34', 'c34'], ['c1', 'c2', 'c3', 'c4']]
df.index = [['r12', 'r12', 'r3'], ['r1', 'r2', 'r3']]
df

       c12    c34
        c1 c2  c3  c4
r12 r1   0  1   2   3
    r2   4  5   6   7
r3  r3   8  9  10  11

리스트 형태로 계층 라벨에 이름을 붙일 수 있다.

In [42]:
df.columns.names = ['cidx1', 'cidx2']
df.index.names = ['ridx1', 'ridx2']
df

cidx1       c12    c34
cidx2        c1 c2  c3  c4
ridx1 ridx2
r12   r1      0  1   2   3
      r2      4  5   6   7
r3    r3      8  9  10  11

# DataFrame 메소드

DataFrame.set_index()로 지정한 컬럼을 인덱스 라벨로 사용할 수 있다.

inplace를 True로 하지 않으면 새 데이터프레임을 만든다.

In [33]:
data = {
    'math': [90, 80, 70],
    'english': [85, 95, 75],
    'science': [90, 85, 80],
    'student': ['Alice', 'Bob', 'Charlie']
}
df = pd.DataFrame(data)

df.set_index('student', inplace=True)
df

         math  english  science
student
Alice      90       85       90
Bob        80       95       85
Charlie    70       75       80

DataFrame.reset_index()로 인덱스 라벨을 지울 수 있다.

drop을 True로 하지 않으면, 인덱스 라벨을 컬럼으로 추가한다.

inplace를 True로 하지 않으면 새 데이터프레임을 만든다.

In [34]:
df.reset_index()

   student  math  english  science
0    Alice    90       85       90
1      Bob    80       95       85
2  Charlie    70       75       80

# DataFrame 연산

컬럼 라벨로 인덱싱 하여 컬럼끼리 연산할 수 있다.

없는 컬럼 라벨에 대입하면, 새로운 컬럼을 추가한다.

In [16]:
data = {
    'math': [90, 80, 70],
    'english': [85, 95, 75],
    'science': [90, 85, 80]
}
df = pd.DataFrame(data)

df['total'] = df['math'] + df['english'] + df['science']

del로 지정한 열을 삭제할 수 있다.

In [17]:
del df['total']

# DataFrame 파일 입출력

데이터프레임을 파일로 저장하고, 불러오는 기능을 제공한다.

불러오면서 Unnamed: 0이 생기는 문제를 해결하기 위해 read_csv 함수에서 index_col을 0으로 지정했다.

In [18]:
data = {
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [20, 25, 30],
    'city': ['Seoul', 'Incheon', 'Busan']
}

df = pd.DataFrame(data)
df.to_csv('test.csv', mode='w', sep=',')

pd.read_csv('test.csv', index_col=0)

      name  age     city
0    Alice   20    Seoul
1      Bob   25  Incheon
2  Charlie   30    Busan