In [2]:
import numpy as np
import pandas as pd

# DataFrame 기본

DataFrame은 표 형태의 2차원 자료구조이다.

index, columns를 직접 지정하여 원하는 라벨을 붙일 수 있다.

딕셔너리를 사용하면 key를 컬럼 라벨로 사용한다.

In [4]:
data = {
    '2022': [12350000, 5437000, 3440200, 2805000],
    '2023': [12352000, 5437200, 3440300, 2805050],
    '2024': [12353000, 5437400, 3440400, 2805100],
    '2025': [12356784, 5437689, 3440451, 2805246],
    '지역': ['수도권', '경상권', '수도권', '경상권'],
    '2015~2019 증가율': [0.0283, 0.0163, 0.0982, 0.0141]
}
df = pd.DataFrame(data,
                  index=['서울', '부산', '인천', '대구'],
                  columns=['지역', '2022', '2023', '2024', '2025', '2015~2019 증가율'])
print(df)

     지역      2022      2023      2024      2025  2015~2019 증가율
서울  수도권  12350000  12352000  12353000  12356784         0.0283
부산  경상권   5437000   5437200   5437400   5437689         0.0163
인천  수도권   3440200   3440300   3440400   3440451         0.0982
대구  경상권   2805000   2805050   2805100   2805246         0.0141

인덱스 라벨과 컬럼 라벨에 이름을 붙일 수 있다.

In [7]:
df.index.name = '도시'
df.columns.name = '특성'
print(df)

특성   지역      2022      2023      2024      2025  2015~2019 증가율
도시
서울  수도권  12350000  12352000  12353000  12356784         0.0283
부산  경상권   5437000   5437200   5437400   5437689         0.0163
인천  수도권   3440200   3440300   3440400   3440451         0.0982
대구  경상권   2805000   2805050   2805100   2805246         0.0141

index는 행 라벨, columns는 열 라벨, values는 실제 값들이다.

In [8]:
print(df.index)
print(df.columns)
print(df.values)

Index(['서울', '부산', '인천', '대구'], dtype='str', name='도시')
Index(['지역', '2022', '2023', '2024', '2025', '2015~2019 증가율'], dtype='str', name='특성')
[['수도권' 12350000 12352000 12353000 12356784 0.0283]
 ['경상권' 5437000 5437200 5437400 5437689 0.0163]
 ['수도권' 3440200 3440300 3440400 3440451 0.0982]
 ['경상권' 2805000 2805050 2805100 2805246 0.0141]]

없는 컬럼에 대입하면, 새 컬럼으로 추가한다.

In [ ]:
df['2022~2025 증가율'] = ((df['2025'] - df['2022']) / df['2022'] * 100).round(2)
print(df)

del 키워드로 컬럼을 삭제할 수 있다.

In [ ]:
del df['2022~2025 증가율']
print(df)

인덱스나 컬럼 라벨을 지정하지 않으면 0, 1, 2, ... 같은 정수 인덱스를 자동으로 붙인다.

In [30]:
pd.DataFrame(np.arange(12).reshape(3, 4))

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

# DataFrame 인덱싱

컬럼 라벨을 사용해 컬럼을 인덱싱할 수 있다.

한 컬럼만 고르면 결과는 Series이다.

여러 컬럼을 고르면 결과는 DataFrame이다.

In [9]:
df['지역']

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: str

In [11]:
df[['2022', '2023']]

특성      2022      2023
도시
서울  12350000  12352000
부산   5437000   5437200
인천   3440200   3440300
대구   2805000   2805050

loc을 사용해 인덱스 라벨 기반으로 인덱싱 할 수 있다.

In [17]:
df.loc['서울']

특성
지역                    수도권
2022             12350000
2023             12352000
2024             12353000
2025             12356784
2015~2019 증가율      0.0283
Name: 서울, dtype: object

In [18]:
df.loc[['부산', '대구']]

특성   지역     2022     2023     2024     2025  2015~2019 증가율
도시
부산  경상권  5437000  5437200  5437400  5437689         0.0163
대구  경상권  2805000  2805050  2805100  2805246         0.0141

In [20]:
df.loc['부산':'대구']

특성   지역     2022     2023     2024     2025  2015~2019 증가율
도시
부산  경상권  5437000  5437200  5437400  5437689         0.0163
인천  수도권  3440200  3440300  3440400  3440451         0.0982
대구  경상권  2805000  2805050  2805100  2805246         0.0141

In [26]:
df.loc[df['2023'] > 5_000_000, ['지역', '2025']]

특성   지역      2025
도시
서울  수도권  12356784
부산  경상권   5437689

iloc을 사용해 정수 인덱스 기반으로 인덱싱할 수 있다.

In [27]:
df.iloc[-1]

특성
지역                   경상권
2022             2805000
2023             2805050
2024             2805100
2025             2805246
2015~2019 증가율     0.0141
Name: 대구, dtype: object

In [28]:
df.iloc[[2, 0]]

특성   지역      2022      2023      2024      2025  2015~2019 증가율
도시
인천  수도권   3440200   3440300   3440400   3440451         0.0982
서울  수도권  12350000  12352000  12353000  12356784         0.0283

In [29]:
df.iloc[1:3]

특성   지역     2022     2023     2024     2025  2015~2019 증가율
도시
부산  경상권  5437000  5437200  5437400  5437689         0.0163
인천  수도권  3440200  3440300  3440400  3440451         0.0982

인덱스에 대해 슬라이싱을 사용할 수 있다. 정수 인덱스와 달리 인덱스 라벨을 사용하면 끝 라벨도 포함한다.

In [13]:
print(df[1:3])
print(df['부산':'대구'])

특성   지역     2022     2023     2024     2025  2015~2019 증가율
도시
부산  경상권  5437000  5437200  5437400  5437689         0.0163
인천  수도권  3440200  3440300  3440400  3440451         0.0982
특성   지역     2022     2023     2024     2025  2015~2019 증가율
도시
부산  경상권  5437000  5437200  5437400  5437689         0.0163
인천  수도권  3440200  3440300  3440400  3440451         0.0982
대구  경상권  2805000  2805050  2805100  2805246         0.0141

컬럼 라벨과 인덱스 라벨을 모두 사용해 원소 하나만 고를 수 있다.

In [14]:
df['2025']['서울']

np.int64(12356784)

컬럼 라벨을 지정하지 않은 경우에만 정수 인덱싱을 사용할 수 있다.

In [35]:
df = pd.DataFrame(np.arange(12).reshape(3, 4))
df[2]

0     2
1     6
2    10
Name: 2, dtype: int64

리스트의 리스트 형태를 사용하여 계층으로 라벨을 지정할 수 있다.

In [41]:
df.columns = [['c12', 'c12', 'c34', 'c34'], ['c1', 'c2', 'c3', 'c4']]
df.index = [['r12', 'r12', 'r3'], ['r1', 'r2', 'r3']]
df

       c12    c34
        c1 c2  c3  c4
r12 r1   0  1   2   3
    r2   4  5   6   7
r3  r3   8  9  10  11

리스트 형태로 계층 라벨에 이름을 붙일 수 있다.

In [42]:
df.columns.names = ['cidx1', 'cidx2']
df.index.names = ['ridx1', 'ridx2']
df

cidx1       c12    c34
cidx2        c1 c2  c3  c4
ridx1 ridx2
r12   r1      0  1   2   3
      r2      4  5   6   7
r3    r3      8  9  10  11

# DataFrame 메소드

DataFrame.set_index()로 지정한 컬럼을 인덱스 라벨로 사용할 수 있다.

inplace를 True로 하지 않으면 새 데이터프레임을 만든다.

In [33]:
data = {
    'math': [90, 80, 70],
    'english': [85, 95, 75],
    'science': [90, 85, 80],
    'student': ['Alice', 'Bob', 'Charlie']
}
df = pd.DataFrame(data)

df.set_index('student', inplace=True)
df

         math  english  science
student
Alice      90       85       90
Bob        80       95       85
Charlie    70       75       80

DataFrame.reset_index()로 인덱스 라벨을 지울 수 있다.

drop을 True로 하지 않으면, 인덱스 라벨을 컬럼으로 추가한다.

inplace를 True로 하지 않으면 새 데이터프레임을 만든다.

In [34]:
df.reset_index()

   student  math  english  science
0    Alice    90       85       90
1      Bob    80       95       85
2  Charlie    70       75       80

# DataFrame 연산

컬럼 라벨로 인덱싱 하여 컬럼끼리 연산할 수 있다.

없는 컬럼 라벨에 대입하면, 새로운 컬럼을 추가한다.

In [16]:
data = {
    'math': [90, 80, 70],
    'english': [85, 95, 75],
    'science': [90, 85, 80]
}
df = pd.DataFrame(data)

df['total'] = df['math'] + df['english'] + df['science']

del로 지정한 열을 삭제할 수 있다.

In [17]:
del df['total']

# DataFrame 파일 입출력

데이터프레임을 파일로 저장하고, 불러오는 기능을 제공한다.

불러오면서 Unnamed: 0이 생기는 문제를 해결하기 위해 read_csv 함수에서 index_col을 0으로 지정했다.

In [18]:
data = {
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [20, 25, 30],
    'city': ['Seoul', 'Incheon', 'Busan']
}

df = pd.DataFrame(data)
df.to_csv('test.csv', mode='w', sep=',')

pd.read_csv('test.csv', index_col=0)

      name  age     city
0    Alice   20    Seoul
1      Bob   25  Incheon
2  Charlie   30    Busan