In [1]:
import numpy as np
import pandas as pd

# DataFrame 기본

DataFrame은 표 형태의 2차원 자료구조이다.

index, columns를 직접 지정하여 원하는 라벨을 붙일 수 있다.

딕셔너리를 사용하면 key를 컬럼 라벨로 사용한다.

In [2]:
data = {
    '2022': [12350000, 5437000, 3440200, 2805000],
    '2023': [12352000, 5437200, 3440300, 2805050],
    '2024': [12353000, 5437400, 3440400, 2805100],
    '2025': [12356784, 5437689, 3440451, 2805246],
    '지역': ['수도권', '경상권', '수도권', '경상권'],
    '2015~2019 증가율': [0.0283, 0.0163, 0.0982, 0.0141]
}
df = pd.DataFrame(data,
                  index=['서울', '부산', '인천', '대구'],
                  columns=['지역', '2022', '2023', '2024', '2025', '2015~2019 증가율'])
print(df)

     지역      2022      2023      2024      2025  2015~2019 증가율
서울  수도권  12350000  12352000  12353000  12356784         0.0283
부산  경상권   5437000   5437200   5437400   5437689         0.0163
인천  수도권   3440200   3440300   3440400   3440451         0.0982
대구  경상권   2805000   2805050   2805100   2805246         0.0141

인덱스 라벨과 컬럼 라벨에 이름을 붙일 수 있다.

In [3]:
df.index.name = '도시'
df.columns.name = '특성'
print(df)

특성   지역      2022      2023      2024      2025  2015~2019 증가율
도시
서울  수도권  12350000  12352000  12353000  12356784         0.0283
부산  경상권   5437000   5437200   5437400   5437689         0.0163
인천  수도권   3440200   3440300   3440400   3440451         0.0982
대구  경상권   2805000   2805050   2805100   2805246         0.0141

index는 행 라벨, columns는 열 라벨, values는 실제 값들이다.

In [4]:
print(df.index)
print(df.columns)
print(df.values)

Index(['서울', '부산', '인천', '대구'], dtype='str', name='도시')
Index(['지역', '2022', '2023', '2024', '2025', '2015~2019 증가율'], dtype='str', name='특성')
[['수도권' 12350000 12352000 12353000 12356784 0.0283]
 ['경상권' 5437000 5437200 5437400 5437689 0.0163]
 ['수도권' 3440200 3440300 3440400 3440451 0.0982]
 ['경상권' 2805000 2805050 2805100 2805246 0.0141]]

없는 컬럼에 대입하면, 새 컬럼으로 추가한다.

In [5]:
df['2022~2025 증가율'] = ((df['2025'] - df['2022']) / df['2022'] * 100).round(2)
print(df)

특성   지역      2022      2023      2024      2025  2015~2019 증가율  2022~2025 증가율
도시
서울  수도권  12350000  12352000  12353000  12356784         0.0283           0.05
부산  경상권   5437000   5437200   5437400   5437689         0.0163           0.01
인천  수도권   3440200   3440300   3440400   3440451         0.0982           0.01
대구  경상권   2805000   2805050   2805100   2805246         0.0141           0.01

del 키워드로 컬럼을 삭제할 수 있다.

In [6]:
del df['2022~2025 증가율']
print(df)

특성   지역      2022      2023      2024      2025  2015~2019 증가율
도시
서울  수도권  12350000  12352000  12353000  12356784         0.0283
부산  경상권   5437000   5437200   5437400   5437689         0.0163
인천  수도권   3440200   3440300   3440400   3440451         0.0982
대구  경상권   2805000   2805050   2805100   2805246         0.0141

인덱스나 컬럼 라벨을 지정하지 않으면 0, 1, 2, ... 같은 정수 인덱스를 자동으로 붙인다.

In [7]:
pd.DataFrame(np.arange(12).reshape(3, 4))

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

# DataFrame 인덱싱

컬럼 라벨을 사용해 컬럼을 인덱싱할 수 있다.

한 컬럼만 고르면 결과는 Series이다.

여러 컬럼을 고르면 결과는 DataFrame이다.

In [8]:
df['지역']

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: str

In [9]:
df[['2022', '2023']]

특성      2022      2023
도시
서울  12350000  12352000
부산   5437000   5437200
인천   3440200   3440300
대구   2805000   2805050

loc을 사용해 인덱스 라벨 기반으로 인덱싱 할 수 있다.

In [10]:
df.loc['서울']

특성
지역                    수도권
2022             12350000
2023             12352000
2024             12353000
2025             12356784
2015~2019 증가율      0.0283
Name: 서울, dtype: object

In [11]:
df.loc[['부산', '대구']]

특성   지역     2022     2023     2024     2025  2015~2019 증가율
도시
부산  경상권  5437000  5437200  5437400  5437689         0.0163
대구  경상권  2805000  2805050  2805100  2805246         0.0141

In [12]:
df.loc['부산':'대구']

특성   지역     2022     2023     2024     2025  2015~2019 증가율
도시
부산  경상권  5437000  5437200  5437400  5437689         0.0163
인천  수도권  3440200  3440300  3440400  3440451         0.0982
대구  경상권  2805000  2805050  2805100  2805246         0.0141

In [13]:
df.loc[df['2023'] > 5_000_000, ['지역', '2025']]

특성   지역      2025
도시
서울  수도권  12356784
부산  경상권   5437689

iloc을 사용해 정수 인덱스 기반으로 인덱싱할 수 있다.

In [14]:
df.iloc[-1]

특성
지역                   경상권
2022             2805000
2023             2805050
2024             2805100
2025             2805246
2015~2019 증가율     0.0141
Name: 대구, dtype: object

In [15]:
df.iloc[[2, 0]]

특성   지역      2022      2023      2024      2025  2015~2019 증가율
도시
인천  수도권   3440200   3440300   3440400   3440451         0.0982
서울  수도권  12350000  12352000  12353000  12356784         0.0283

In [16]:
df.iloc[1:3]

특성   지역     2022     2023     2024     2025  2015~2019 증가율
도시
부산  경상권  5437000  5437200  5437400  5437689         0.0163
인천  수도권  3440200  3440300  3440400  3440451         0.0982

인덱스에 대해 슬라이싱을 사용할 수 있다. 정수 인덱스와 달리 인덱스 라벨을 사용하면 끝 라벨도 포함한다.

In [17]:
print(df[1:3])
print(df['부산':'대구'])

특성   지역     2022     2023     2024     2025  2015~2019 증가율
도시
부산  경상권  5437000  5437200  5437400  5437689         0.0163
인천  수도권  3440200  3440300  3440400  3440451         0.0982
특성   지역     2022     2023     2024     2025  2015~2019 증가율
도시
부산  경상권  5437000  5437200  5437400  5437689         0.0163
인천  수도권  3440200  3440300  3440400  3440451         0.0982
대구  경상권  2805000  2805050  2805100  2805246         0.0141

컬럼 라벨과 인덱스 라벨을 모두 사용해 원소 하나만 고를 수 있다.

In [18]:
df['2025']['서울']

np.int64(12356784)

컬럼 라벨을 지정하지 않은 경우에만 정수 인덱싱을 사용할 수 있다.

In [19]:
df = pd.DataFrame(np.arange(12).reshape(3, 4))
df[2]

0     2
1     6
2    10
Name: 2, dtype: int64

# DataFrame 인덱스 조작

In [20]:
df = pd.DataFrame(
        np.vstack([list("ABCDE"), np.round(np.random.rand(3, 5), 2)]).T,
        columns=["c1", "c2", "c3", "c4"],
    )
df

  c1    c2    c3    c4
0  A  0.36  0.48  0.58
1  B  0.82  0.57  0.47
2  C  0.41  0.36  0.72
3  D  0.91  0.51  0.49
4  E   0.1  0.32  0.43

set_index()는 기존 컬럼 하나를 인덱스 라벨로 바꾼다.

In [21]:
df2 = df.set_index('c1')
df2

      c2    c3    c4
c1
A   0.36  0.48  0.58
B   0.82  0.57  0.47
C   0.41  0.36  0.72
D   0.91  0.51  0.49
E    0.1  0.32  0.43

reset_index()는 인덱스 라벨을 없애고 컬럼으로 추가한다.

In [22]:
df2.reset_index()

  c1    c2    c3    c4
0  A  0.36  0.48  0.58
1  B  0.82  0.57  0.47
2  C  0.41  0.36  0.72
3  D  0.91  0.51  0.49
4  E   0.1  0.32  0.43

drop을 True로 하면 컬럼으로 추가하지 않고 버린다.

In [23]:
df2.reset_index(drop=True)

     c2    c3    c4
0  0.36  0.48  0.58
1  0.82  0.57  0.47
2  0.41  0.36  0.72
3  0.91  0.51  0.49
4   0.1  0.32  0.43

Multi index는 인덱스나 컬럼에 계층 구조를 만든다.

In [24]:
df = pd.DataFrame(
    np.round(np.random.randn(6, 4), 2),
    columns=[["A", "A", "B", "B"], ["C1", "C2", "C3", "C4"]],
    index=[["M", "M", "M", "F", "F", "F"], [f"id_{i+1}" for i in range(3)] * 2]
)
df.columns.names = ["Cidx1", "Cidx2"]
df.index.names = ["Ridx1", "Ridx2"]
print(df)

Cidx1           A           B
Cidx2          C1    C2    C3    C4
Ridx1 Ridx2
M     id_1  -1.01 -0.38  0.65 -0.42
      id_2  -1.97 -1.14  0.41 -0.50
      id_3   0.05 -0.90 -0.60  0.59
F     id_1   0.84 -0.50 -0.96  0.22
      id_2  -1.28 -0.32 -2.41  0.01
      id_3  -0.58 -0.23  3.61  0.85

stack()은 컬럼을 인덱스로 쌓는다.

In [25]:
df.stack('Cidx1')

Cidx2                C1    C2    C3    C4
Ridx1 Ridx2 Cidx1
M     id_1  A     -1.01 -0.38   NaN   NaN
            B       NaN   NaN  0.65 -0.42
      id_2  A     -1.97 -1.14   NaN   NaN
            B       NaN   NaN  0.41 -0.50
      id_3  A      0.05 -0.90   NaN   NaN
            B       NaN   NaN -0.60  0.59
F     id_1  A      0.84 -0.50   NaN   NaN
            B       NaN   NaN -0.96  0.22
      id_2  A     -1.28 -0.32   NaN   NaN
            B       NaN   NaN -2.41  0.01
      id_3  A     -0.58 -0.23   NaN   NaN
            B       NaN   NaN  3.61  0.85

unstack()은 인덱스를 컬럼으로 쌓는다.

In [26]:
df.unstack('Ridx2')

Cidx1     A                                   B
Cidx2    C1                C2                C3                C4
Ridx2  id_1  id_2  id_3  id_1  id_2  id_3  id_1  id_2  id_3  id_1  id_2  id_3
Ridx1
F      0.84 -1.28 -0.58 -0.50 -0.32 -0.23 -0.96 -2.41  3.61  0.22  0.01  0.85
M     -1.01 -1.97  0.05 -0.38 -1.14 -0.90  0.65  0.41 -0.60 -0.42 -0.50  0.59

# DataFrame 연산

컬럼 라벨로 인덱싱 하여 컬럼끼리 연산할 수 있다.

없는 컬럼 라벨에 대입하면, 새로운 컬럼을 추가한다.

In [27]:
data = {
    'math': [90, 80, 70],
    'english': [85, 95, 75],
    'science': [90, 85, 80]
}
df = pd.DataFrame(data)

df['total'] = df['math'] + df['english'] + df['science']

# DataFrame 집계

NaN은 결측값(값이 없음)을 의미한다.

count()로 NaN을 제외한 개수를 셀 수 있다.

In [28]:
s = pd.Series(range(10), dtype=float)
s[3] = np.nan
s.count()

np.int64(9)

In [29]:
df = pd.DataFrame(np.random.randint(5, size=(4, 4)), dtype=float)
df.iloc[2, 3] = np.nan
df.count()

0    4
1    4
2    4
3    3
dtype: int64

sort_values()는 값을 기준으로 정렬한다.

ascending이 True면 오름차순 정렬한다.

by는 지정한 컬럼을 정렬의 기준으로 삼는다.

In [30]:
s.sort_values(ascending=False)

9    9.0
8    8.0
7    7.0
6    6.0
5    5.0
4    4.0
2    2.0
1    1.0
0    0.0
3    NaN
dtype: float64

In [31]:
df.sort_values(by=2)

     0    1    2    3
1  1.0  4.0  0.0  2.0
2  1.0  2.0  0.0  NaN
0  3.0  3.0  1.0  4.0
3  4.0  1.0  1.0  2.0

value_counts()는 각 값이 몇 번 나타났는지 센다.

In [32]:
s = pd.Series(np.random.randint(6, size=100))
s.value_counts()

2    23
4    22
5    19
3    17
0    13
1     6
Name: count, dtype: int64

sort_index()는 인덱스를 기준으로 정렬한다.

In [33]:
s.value_counts().sort_index()

0    13
1     6
2    23
3    17
4    22
5    19
Name: count, dtype: int64

sum()은 axis=0이면 열 방향, axis=1이면 행 방향으로 합을 계산한다.

In [34]:
df = pd.DataFrame(np.random.randint(10, size=(4, 8)))
df

   0  1  2  3  4  5  6  7
0  6  4  4  6  6  4  0  4
1  3  1  8  3  7  5  5  9
2  2  0  0  2  9  2  1  1
3  2  1  8  2  5  9  6  4

In [35]:
df.sum()

0    13
1     6
2    20
3    13
4    27
5    20
6    12
7    18
dtype: int64

In [36]:
df.sum(axis=1)

0    34
1    41
2    17
3    37
dtype: int64

apply()를 사용하면 행 또는 열 단위로 사용자 정의 함수를 적용할 수 있다.

axis=0이면 기본인 열에, axis=1이면 행에 적용한다.

In [37]:
df = pd.DataFrame({
    'A': [1, 3, 1, 3, 4],
    'B': [2, 3, 1, 2, 3],
    'C': [1, 3, 2, 4, 4],
})
df

   A  B  C
0  1  2  1
1  3  3  3
2  1  1  2
3  3  2  4
4  4  3  4

In [38]:
df.apply(lambda x: x.max() - x.min())

A    3
B    2
C    3
dtype: int64

In [39]:
df.apply(lambda x: x.max() - x.min(), axis=1)

0    1
1    0
2    1
3    2
4    1
dtype: int64

In [40]:
freq_table = df.apply(lambda x: x.value_counts(), axis=0)
freq_table

     A    B  C
1  2.0  1.0  1
2  NaN  2.0  1
3  2.0  2.0  1
4  1.0  NaN  2

fillna()는 NaN을 원하는 값으로 채운다.

In [41]:
freq_table.fillna(0.0).astype(int)

   A  B  C
1  2  1  1
2  0  2  1
3  2  2  1
4  1  0  2

cut()은 숫자 데이터를 구간으로 나누어 범주형 데이터로 바꾼다.

In [42]:
ages = [0, 2, 10, 21, 23, 37, 31, 61, 20, 41, 80, 101]
bins = [1, 20, 30, 50, 70, 100]
labels = ["미성년자", "청년", "중년", "장년", "노년"]
result = pd.cut(ages, bins=bins, labels=labels)
print(result)
print("categories:", result.categories)
print("codes:", result.codes)

[NaN, '미성년자', '미성년자', '청년', '청년', ..., '장년', '미성년자', '중년', '노년', NaN]
Length: 12
Categories (5, str): ['미성년자' < '청년' < '중년' < '장년' < '노년']
categories: Index(['미성년자', '청년', '중년', '장년', '노년'], dtype='str')
codes: [-1  0  0  1  1  2  2  3  0  2  4 -1]

# DataFrame 파일 입출력

데이터프레임을 파일로 저장하고, 불러오는 기능을 제공한다.

불러오면서 Unnamed: 0이 생기는 문제를 해결하기 위해 read_csv 함수에서 index_col을 0으로 지정했다.

In [43]:
data = {
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [20, 25, 30],
    'city': ['Seoul', 'Incheon', 'Busan']
}

df = pd.DataFrame(data)
df.to_csv('test.csv', mode='w', sep=',')

pd.read_csv('test.csv', index_col=0)

      name  age     city
0    Alice   20    Seoul
1      Bob   25  Incheon
2  Charlie   30    Busan